
steps:
  clone-xtraplatform:
    image: woodpeckerci/plugin-git:2.10.1@sha256:550075c844fcec0af41d9d28f9860aa5d8c43e1e9419be4b9266dc02c2f29804
    settings:
      remote: https://github.com/ldproxy/xtraplatform.git
      branch: master
      path: ../xtraplatform
      ref: refs/heads/master
      sha: ''
    when:
      event: [ push ]
      branch: [ renovate-* ]

  test-xtraplatform:
    image: eclipse-temurin:25@sha256:dcf835e52330939b6c9f90ecab8aafcbcaa8fbf48423db44de884cf978c10144
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - cd ../xtraplatform
      - ./gradlew check -Pbuild-plugins=true
    when:
      event: [ push ]
      branch: [ renovate-* ]
