
steps:
  clone-xtraplatform:
    image: woodpeckerci/plugin-git@sha256:e6326a142d9bf08c6cc79cee3b3b26c87c15c999f89fb0b14c98d6031639968a
    settings:
      remote: https://github.com/ldproxy/xtraplatform.git
      branch: master
      path: ../xtraplatform
      ref: refs/heads/master
      sha: ''
    when:
      event: [ push ]
      branch: [ renovate-* ]

  test-xtraplatform:
    image: eclipse-temurin:21@sha256:e58e492628c1428ceb838afc1a1b8762673d5eaa09296f560c363daea0fdcf3b
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - cd ../xtraplatform
      - ./gradlew check -Pbuild-plugins=true
    when:
      event: [ push ]
      branch: [ renovate-* ]
