
steps:
  clone-xtraplatform:
    image: woodpeckerci/plugin-git:2.9.2@sha256:ebde4a4d07e0e24b630082484d192890dd4f6d442d90bf5466f0763860f83652
    settings:
      remote: https://github.com/ldproxy/xtraplatform.git
      branch: master
      path: ../xtraplatform
      ref: refs/heads/master
      sha: ''
    when:
      event: [ push ]
      branch: [ renovate-* ]

  test-xtraplatform:
    image: eclipse-temurin:25@sha256:12e44624adee6808a36d962717e1656e0afeeeff5a100f9cb00e0136513558f0
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - cd ../xtraplatform
      - ./gradlew check -Pbuild-plugins=true
    when:
      event: [ push ]
      branch: [ renovate-* ]
