
steps:
  clone-xtraplatform:
    image: woodpeckerci/plugin-git
    settings:
      remote: https://github.com/ldproxy/xtraplatform.git
      branch: master
      path: ../xtraplatform
      ref: refs/heads/master
      sha: ''
    when:
      event: [ push ]
      branch: [ renovate-* ]

  test-xtraplatform:
    image: openjdk:11-slim
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - cd ../xtraplatform
      - ./gradlew check -Pbuild-plugins=true
    when:
      event: [ push ]
      branch: [ renovate-* ]
