depends_on:
  - check

when:
  event: [push, tag]

steps:
  load-cache:
    image: drillster/drone-volume-cache@sha256:b82e143081dfb04ba300ce7854dfcecd31e7858e1998bf89806ec74a80a78e94
    volumes: [/var/lib/docker/tmp:/cache]
    settings:
      restore: true
      mount:
        - .gradle/caches
        - .gradle/wrapper

  build:
    image: eclipse-temurin:11@sha256:c209d7d4b04578d9f420f54865ba6b3c94904b3bce8b4131a6db20ebe15439b0
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build -Pbranch=$CI_COMMIT_BRANCH
    when:
      event: push

  build-release:
    image: eclipse-temurin:11@sha256:c209d7d4b04578d9f420f54865ba6b3c94904b3bce8b4131a6db20ebe15439b0
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build -Prelease=true
    when:
      event: tag

  publish-snapshot:
    image: eclipse-temurin:11@sha256:c209d7d4b04578d9f420f54865ba6b3c94904b3bce8b4131a6db20ebe15439b0
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
    when:
      event: push

  publish-release:
    image: eclipse-temurin:11@sha256:c209d7d4b04578d9f420f54865ba6b3c94904b3bce8b4131a6db20ebe15439b0
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish -Prelease=true -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
    when:
      event: tag

  save-cache:
    image: drillster/drone-volume-cache@sha256:b82e143081dfb04ba300ce7854dfcecd31e7858e1998bf89806ec74a80a78e94
    volumes: [/var/lib/docker/tmp:/cache]
    settings:
      rebuild: true
      mount:
        - .gradle/caches
        - .gradle/wrapper
