depends_on:
  - check

when:
  event: [push, tag]

steps:
  load-cache:
    image: drillster/drone-volume-cache
    volumes: [/var/lib/docker/tmp:/cache]
    settings:
      restore: true
      mount:
        - .gradle/caches
        - .gradle/wrapper

  build:
    image: eclipse-temurin:11
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build -Pbranch=$CI_COMMIT_BRANCH
    when:
      event: push

  build-release:
    image: eclipse-temurin:11
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew build -Prelease=true
    when:
      event: tag

  publish-snapshot:
    image: eclipse-temurin:11
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish -Pbranch=$CI_COMMIT_BRANCH -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
    when:
      event: push

  publish-release:
    image: eclipse-temurin:11
    commands:
      - export GRADLE_USER_HOME=$${DRONE_WORKSPACE}/.gradle
      - ./gradlew publish -Prelease=true -PdeployUser=$DEPLOY_USER -PdeployPassword=$DEPLOY_PASSWORD
    secrets: [ deploy_user, deploy_password]
    when:
      event: tag

  save-cache:
    image: drillster/drone-volume-cache
    volumes: [/var/lib/docker/tmp:/cache]
    settings:
      rebuild: true
      mount:
        - .gradle/caches
        - .gradle/wrapper
